# Generated by Django 6.0.3 on 2026-04-09 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapaGeografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_capa', models.CharField(help_text='Ej: Curvas de nivel maestras', max_length=150)),
                ('estado', models.CharField(help_text='Se selecciona desde el formulario', max_length=50)),
                ('municipio', models.CharField(help_text='Se selecciona desde el formulario', max_length=100)),
                ('categoria', models.CharField(choices=[('ALTIMETRIA', 'Altimetría'), ('CATASTRO', 'Catastro'), ('EQUIPAMIENTO', 'Equipamiento Urbano'), ('ESTRUCTURA', 'Estructura Urbana'), ('HIDROLOGIA', 'Hidrología'), ('INFRAESTRUCTURA', 'Infraestructura'), ('TOPOGRAFIA', 'Topografía'), ('USOS_PREDIO', 'Usos de Predio'), ('VEGETACION', 'Vegetación'), ('VIAS', 'Vías'), ('IZUCAR', 'Izúcar (Proyectos Especiales)'), ('OTROS', 'Otros')], max_length=20)),
                ('tipo_geometria', models.CharField(choices=[('PUNTOS', 'Punto / MultiPunto'), ('LINEAS', 'Línea / MultiLineString'), ('POLIGONOS', 'Polígono / MultiPolígono')], max_length=20)),
                ('archivo_original', models.FileField(upload_to='geojsons/originales/%Y/%m/')),
                ('datos_normalizados', models.JSONField(help_text='GeoJSON con atributos estandarizados y limpios')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capa Geográfica',
                'verbose_name_plural': 'Capas Geográficas',
                'indexes': [models.Index(fields=['estado', 'municipio', 'categoria'], name='upload_fiel_estado_9ac178_idx')],
            },
        ),
    ]
