# Generated by Django 6.0.3 on 2026-04-14 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, help_text='Folio generado automáticamente (ej: PROY-2026-0001)', max_length=30, unique=True)),
                ('nombre_proyecto', models.CharField(help_text='Nombre descriptivo del proyecto', max_length=200)),
                ('anio', models.PositiveIntegerField(help_text='Año del proyecto')),
                ('estado', models.CharField(help_text='Estado de la república', max_length=50)),
                ('municipio', models.CharField(help_text='Municipio', max_length=100)),
                ('categoria', models.CharField(choices=[('ALTIMETRIA', 'Altimetría'), ('CATASTRO', 'Catastro'), ('EQUIPAMIENTO', 'Equipamiento Urbano'), ('ESTRUCTURA', 'Estructura Urbana'), ('HIDROLOGIA', 'Hidrología'), ('INFRAESTRUCTURA', 'Infraestructura'), ('TOPOGRAFIA', 'Topografía'), ('USOS_PREDIO', 'Usos de Predio'), ('VEGETACION', 'Vegetación'), ('VIAS', 'Vías'), ('OTROS', 'Otros')], max_length=20)),
                ('tipo_escala', models.CharField(choices=[('1:500', '1:500'), ('1:1000', '1:1,000'), ('1:2000', '1:2,000'), ('1:5000', '1:5,000'), ('1:10000', '1:10,000'), ('1:20000', '1:20,000'), ('1:50000', '1:50,000'), ('OTRA', 'Otra')], max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado', 'municipio', 'categoria'], name='projects_pr_estado_b23734_idx'), models.Index(fields=['folio'], name='projects_pr_folio_d21486_idx')],
            },
        ),
    ]
