# Generated by Django 6.0.3 on 2026-04-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='avance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de avance del proyecto (0.00 - 100.00)', max_digits=5),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fases',
            field=models.JSONField(blank=True, default=list, help_text='Lista de fases del proyecto. Ej: [{"nombre": "Levantamiento", "completada": false}]'),
        ),
    ]
